#!/bin/bash

CONFIG_FILE=".githooks/hook-config.cfg"
source $CONFIG_FILE

# Check the exit code of the previous command (source)
if [ $? -eq 0 ]; then
  echo "Config file loaded successfully"
else
  echo "Error: Failed to load config file"
  # Optionally, exit the script with a specific code
  exit 1
fi



# Check if the pre-push hook is enabled
if [ "$ENABLE_HOOK" != "true" ]; then
    echo "Pre-push hook is disabled. Skipping build."
    exit 0
else
    echo "Pre-push hook enabled"
fi

# Navigate to the backend directory
cd backend

# Run the build command
colcon build

# Check if the build was successful
if [ $? -ne 0 ]; then
    echo "Build failed. Aborting push."
    echo ""  # Add a new line
    exit 1
else
    echo "Build succeeded. Proceeding with push."
    echo ""  # Add a new line
fi

# Navigate back to the root directory
cd ..

exit 0
