#!/bin/bash

enable_hook=${ENABLE_HOOK:-true}


# Check if the pre-push hook is enabled
if [ "$enable_hook" != "true" ]; then
    echo "Pre-push hook is disabled. Skipping build."
    echo ""    
    exit 0
else
    echo "Pre-push hook enabled"
    echo ""
fi

# Navigate to the backend directory
cd backend

# Run the build command
colcon build

# Check if the build was successful
if [ $? -ne 0 ]; then
    echo "Build failed. Aborting push."
    echo ""  # Add a new line
    exit 1
else
    echo "Build succeeded. Proceeding with push."
    echo ""  # Add a new line
fi

# Navigate back to the root directory
cd ..

exit 0
